version: '3.8'

services:
  backend:
    build: ./backend
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 8000:8000
    environment:
      - ENVIRONMENT=dev
      - TESTING=1
      - DATABASE_URL=sqlite:///./prod.db

  frontend:
    build: ./frontend
    command: npm start
    volumes:
      - ./frontend:/app
    expose:
      - 3000
    ports:
      - 3000:3000
